# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
    copyright: 2025
    project: Seminar Manager
    version: 5.9
    release: 5.9.0
    latex_documents:
    -   - Index
        - seminars.tex
        - Seminar Manager
        - Oliver Klee
        - manual
    latex_elements:
        papersize: a4paper
        pointsize: 10pt
        preamble: \usepackage{typo3}
    latex_use_parts: True
    latex_show_pagerefs: True
    intersphinx_mapping:
        restdoc:
        - https://docs.typo3.org/typo3cms/extensions/restdoc/
        - null
        t3tsref:
        - https://docs.typo3.org/typo3cms/TyposcriptReference/
        - null
...
